# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "ghcr.io"
  repository: "roman-98/telebot"
  tag: "1.0.0-yu483iu-linux-amd64"
  os: linux
  arch: amd64
secret:
  name: "telebot"
  tokenName: "TELE_TOKEN"
  tokenKey: "token"

